In [1]:
# 1. Импортировать NumPy
import numpy as np

In [2]:
# 2. Напечатать версию и конфигурацию
print(np.__version__)

1.14.2


In [3]:
# 3. Создать вектор (одномерный массив) размера 10, заполненый нулями
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4. Создать вектор размер 10, заполненный единицами
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 5. Создать вектор размера 10, заполненный числом 2.5
np.full([10], 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# 6. Получить документацию о функции numpy.add из командной строки
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [7]:
# 7. Создать вектор заполненный нулями, но пятый элемент равен 1
v = np.zeros([10])
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 8. Создать вектор со значениями от 10 до 49
v = np.arange(start=10,stop=50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# 9. Развернуть вектор (первый становится последним)
v = np.arange(start=1, stop=11)
v = v[::-1]
v

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
# 10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
m = np.arange(0,9).reshape(3,3)
np.reshape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

# -----------вариант 1.-----------
np.nonzero([1,2,0,0,4,0])

# -----------вариант 2.-----------
v = np.array([1,2,0,0,4,0])
print(np.where(v != 0))

(array([0, 1, 4], dtype=int32),)


In [12]:
# 12. Создать единичную матрицу 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 13. Создать массив 3x3x3 со случайными значениями
np.random.random([3,3,3])

array([[[0.32291579, 0.1255343 , 0.45234206],
        [0.64773031, 0.70784262, 0.11189862],
        [0.40829003, 0.3652753 , 0.56822345]],

       [[0.6468966 , 0.90611791, 0.40679089],
        [0.75234845, 0.91611659, 0.80578544],
        [0.13033221, 0.18423419, 0.6321614 ]],

       [[0.05615199, 0.73601337, 0.93948249],
        [0.20114759, 0.99311374, 0.11286063],
        [0.52628624, 0.05564345, 0.06780602]]])

In [14]:
# 14. Создать массив 10x10 со случайными значениями, найти минимум и максимум
m = np.random.random([10,10])

# -----------вариант 1.-----------
max_var1, max_var2 = m.min(), m.max()
print(max_var1, max_var2)

print()

# -----------вариант 2.-----------
min_var2 = np.min(m)
max_var2 = np.max(m)
print(min_var2)
print(max_var2)

0.019431913387810584 0.9986488697028484

0.019431913387810584
0.9986488697028484


In [15]:
# 15. Создать случайный вектор размера 30 и найти среднее значение всех элементов
v = np.random.random([30])
v.mean()

0.4691686753574416

In [16]:
# 16. Создать матрицу с 0 внутри и 1 на границах

# -----------вариант 1.-----------
m = np.ones([10,10])
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# 17. Выяснить результат следующих выражений
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [10]:
# 18. Создать 5x5 матрицу с 1,2,3,4 под диагональю

# -----------Вариант 1.-----------
# Решение в интернете, но я хотел чтобы было добавление с двух сторон k-+1
# и была возможность добавления на существующую матрицу

m = np.diag(np.arange(1, 5), k=-1)

print('Вариант 1')
print(m)

# -----------Вариант 2.-----------
# Тяжелый и неправильный вариант. Созданы 4 лишних переменные.

m = np.arange(1, 26).reshape([5,5])

# создаем доп. матрицы с нужными диагоналями
d1 = np.diag(np.arange(1, m.shape[0]), k=-1)
d2 = np.diag(np.arange(1, m.shape[0]), k=1)

# получаем индексы, которые удовлетворяют условию
ind1 = np.where(d1>0)
ind2 = np.where(d2>0)

# присвоение значений по индексам
m[ind1] = 0
m[ind2] = 0

print('Вариант 2')
print(m)

# -----------Вариант 3.-----------
# Легкий варинат без создания дополнительной матрицы

# определим функцию, которая возвращает индексы в зависимсоти от смещения (k) матрицы (m)

def diag_indices_k(m, k):
    
    """ функция возвращает индексы диагональных элементов матрицы (m) со смещением (k) """
    
    rows, cols = np.diag_indices_from(m)
    if k < 0:
        return rows[-k:], cols[:k]
    elif k > 0:
        return rows[:-k], cols[k:]
    else:
        return rows, cols

# создаем матрицу (m)
m = np.arange(1, 26).reshape([5,5])
# проставляем со смещением диагональные значения
m[diag_indices_k(m, -1)] = 0
m[diag_indices_k(m, 1)] = 0
print('Вариант 3')
print(m)


Вариант 1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
Вариант 2
[[ 1  0  3  4  5]
 [ 0  7  0  9 10]
 [11  0 13  0 15]
 [16 17  0 19  0]
 [21 22 23  0 25]]
Вариант 3
[[ 1  0  3  4  5]
 [ 0  7  0  9 10]
 [11  0 13  0 15]
 [16 17  0 19  0]
 [21 22 23  0 25]]


In [12]:
# 19. Создать матрицу 8x8 и заполнить ее в шахматном порядке
m = np.zeros([8,8])
m[::2, ::2] = 1
m[1::2, 1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [20]:
# 20. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [59]:
# 21. Создать матрицу 8x8 и заполнить ее в шахматном порядке, используя функцию tile

# -----------Вариант 1.-----------
m = np.tile(np.array([[1,0], [0,1]]), [4,4])
print('вариант 1')
print(m)
print()
# -----------Вариант 2 (первое что пришло в голову).-----------
# тяжелый вариант
begin = np.array([0,1])
m = np.tile(begin, [8,5])
m[::2,0:-1] = m[::2,1:]
m = m[:,:-2]
print('вариант 2')
print(m)

вариант 1
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

вариант 2
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [76]:
# 22. Перемножить матрицы 5x3 и 3x2

a = np.random.random([5,3])
b = np.random.random([3,2])
print(np.dot(a,b))


[[0.4222276  0.67511683]
 [0.0687243  0.09106668]
 [0.35918754 0.70697517]
 [0.85124592 0.43071301]
 [0.97899294 0.87300153]]


In [171]:
# 22.1. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки
m = np.random.randint(low=1, high=100, size=[5,7])
print(m)
print()
d = [3,5]
m = np.delete(arr=m, obj=d, axis=1)
print(m)

[[73  7 99  4 53 85 19]
 [17 64 49 43 83 11  9]
 [56 36 42 19 15 93 26]
 [96 39 88 60  4 65 48]
 [59 92 56 42 22 39 39]]

[[73  7 99 53 19]
 [17 64 49 83  9]
 [56 36 42 15 26]
 [96 39 88  4 48]
 [59 92 56 22 39]]


In [172]:
# 23. Дан массив, поменять знак у элементов, значения которых между 3 и 8
# -----------Вариант 1.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
m[(m > 3) & (m < 8)] *=-1
print(m)
print()

# -----------Вариант 2.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
ind = np.where((m > 3) & (m < 8))
m[ind] *=-1
print(m)

[[17 -4 -5 15 19]
 [24  1 11 23 23]
 [-5 12  1 20 23]
 [22 -7  8 -5  8]
 [ 2 -4 22 12 21]]

[[22 13  9  2 16]
 [-5 -7 13 17  3]
 [-4 10 17  2 12]
 [-4 23 13 11 18]
 [ 1 16  8 23 10]]


In [108]:
# 24. Создать матрицу 5x5 со значениями в строках от 0 до 4

# -----------Вариант 1.-----------
print('вариант 1')
m = np.zeros([5,5])
m += np.arange(5)
print(m)
print(m.dtype)
print()
# -----------Вариант 2.-----------
print('вариант 2')
m = np.tile(np.arange(5,dtype='float'),[5,1])
print(m)
print(m.dtype)

вариант 1
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64

вариант 2
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64


In [146]:
# 25. Есть генератор, сделать с его помощью массив
g=([i for i in range(10)] for j in range(5))
g=(i for i in range(10))
np.fromiter(g, dtype='float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [173]:
# 25. Есть генератор, сделать с его помощью массив

# -----------Вариант 1.-----------
# Однако, функция fromiter поддерживает только одномерные массивы (векторы)
def generate():
    for x in range(10):
            yield x
        
m = np.fromiter(generate(), dtype='float', count=-1)
print(m)

# -----------Вариант 2.-----------
# Сделаем, чтобы была возможность преобразовывать и многомерные массивы


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [196]:
# 26. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

# -----------Вариант 1.-----------
print('вариант 1')
v = np.linspace(start=0, stop=1, num=12)[1:-1]
print(v)
print()
# -----------Вариант 2.-----------
print('вариант 2')
v = np.linspace(0,1,11, endpoint=False)
v = v[1:]
print(v)

вариант 1
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]

вариант 2
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [221]:
# 27. Отсортировать вектор

v = np.random.random(size=[10])
v = np.sort(a=v, axis=0)
print(v)


[0.18016463 0.24377808 0.51881267 0.59645635 0.65509912 0.7753623
 0.80574937 0.81813011 0.85278596 0.88155365]


In [226]:
# 28. Проверить, одинаковы ли 2 NumPy массива

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(np.array_equal(a,b))
print(np.allclose(a,b))


True
True


In [228]:
# 29. Сделать массив неизменяемым
m = np.zeros([5,5])
m.flags.writeable = False
m[0] = 1

ValueError: assignment destination is read-only

In [229]:
# 30. Дан массив 10x2 (точки в декартовой системе координат),
# нужно преобразовать в полярную

m = np.random.random([10,2])
x,y = m[:,0], m[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)
print(r)
print(t)

[1.18099562 0.87406186 0.69688492 0.6072008  0.74970337 0.57479907
 0.48523153 1.03595076 0.62338744 0.49429698]
[0.89351812 0.09813441 0.49658762 0.73600869 0.6185531  1.4790168
 1.44706178 0.63051638 1.47286207 0.86981304]


In [283]:
# 31. Заменить максимальный элемент на 0

# -----------Вариант 1.-----------

# Однако, если в массиве будут повторяющиеся минимальные или максимальные элементы,
# то присваивание 0 производиться не будет
m = np.random.random([5,5])
m.flatten()[m.argmax()] = 0
m
# print(m.argmax())
# m[16]

# # -----------Вариант 2.-----------
# m = np.random.randint(low=1, high=10, size=[5,5])
# m[np.where(m == m.min())] = 0
# print()
# print(m)


array([[0.70375586, 0.95574067, 0.19165307, 0.95215953, 0.1297289 ],
       [0.75873515, 0.94873266, 0.72913879, 0.48371332, 0.27451666],
       [0.95845849, 0.90752246, 0.74859691, 0.1650814 , 0.3675887 ],
       [0.9856258 , 0.06776647, 0.65289203, 0.83518134, 0.52124658],
       [0.27540405, 0.92182456, 0.20751392, 0.30906305, 0.84678731]])