In [14]:
# 1. Импортировать NumPy
import numpy as np

In [15]:
# 2. Напечатать версию и конфигурацию
print(np.__version__)

1.14.2


In [16]:
# 3. Создать вектор (одномерный массив) размера 10, заполненый нулями
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# 4. Создать вектор размер 10, заполненный единицами
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# 5. Создать вектор размера 10, заполненный числом 2.5
np.full([10], 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [20]:
# 6. Получить документацию о функции numpy.add из командной строки
help (np.add)

In [21]:
# 7. Создать вектор заполненный нулями, но пятый элемент равен 1
v = np.zeros([10])
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [22]:
# 8. Создать вектор со значениями от 10 до 49
v = np.arange(start=10,stop=50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
# 9. Развернуть вектор (первый становится последним)
v = np.arange(start=1, stop=11)
print('вариант 1')
v1 = v[::-1]
print(v1)
print()
print('вариант 2')
v2 = np.flip(v, 0)
print(v2)

вариант 1
[10  9  8  7  6  5  4  3  2  1]

вариант 2
[10  9  8  7  6  5  4  3  2  1]


In [41]:
# 10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
m = np.arange(0,9).reshape(3,3)
np.reshape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
# 11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

# -----------вариант 1.-----------
print('вариант 1')
print(np.nonzero([1,2,0,0,4,0]))
print()

# -----------вариант 2.-----------
print('вариант 2')
v = np.array([1,2,0,0,4,0])
print(np.where(v != 0))

вариант 1
(array([0, 1, 4], dtype=int32),)

вариант 2
(array([0, 1, 4], dtype=int32),)


In [42]:
# 12. Создать единичную матрицу 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# 13. Создать массив 3x3x3 со случайными значениями
np.random.random([3,3,3])

array([[[0.61052372, 0.21895127, 0.77138185],
        [0.55763167, 0.34263457, 0.51770609],
        [0.08085674, 0.84612361, 0.53404771]],

       [[0.37225285, 0.82630833, 0.9153937 ],
        [0.56062089, 0.81116999, 0.60104827],
        [0.98697149, 0.79233467, 0.34716222]],

       [[0.84559271, 0.17538198, 0.79914408],
        [0.85786202, 0.1850629 , 0.74439501],
        [0.62876836, 0.28752064, 0.58530033]]])

In [44]:
# 14. Создать массив 10x10 со случайными значениями, найти минимум и максимум
m = np.random.random([10,10])

# -----------вариант 1.-----------
max_var1, max_var2 = m.min(), m.max()
print('варинат 1')
print(max_var1, max_var2)
print()

# -----------вариант 2.-----------
print('вариант 2')
min_var2 = np.min(m)
max_var2 = np.max(m)
print(min_var2)
print(max_var2)

варинат 1
0.0030022503405340295 0.9940501825199489

вариант 2
0.0030022503405340295
0.9940501825199489


In [45]:
# 15. Создать случайный вектор размера 30 и найти среднее значение всех элементов
v = np.random.random([30])
v.mean()

0.4803450402995165

In [46]:
# 16. Создать матрицу с 0 внутри и 1 на границах

# -----------вариант 1.-----------
m = np.ones([10,10])
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
# 17. Выяснить результат следующих выражений
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [151]:
# 18. Создать 5x5 матрицу с 1,2,3,4 под диагональю

# -----------Вариант 1.-----------
# Решение в интернете, но я хотел чтобы было добавление с двух сторон k-+1
# и была возможность добавления на существующую матрицу

m = np.diag(np.arange(1, 5), k=-1)

print()
print('Вариант 1')
print(m)

# -----------Вариант 2.-----------
# Тяжелый и неправильный вариант. Созданы 4 лишних переменные.

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# создаем доп. матрицы с нужными диагоналями
d1 = np.diag(np.arange(1, m.shape[0]), k=-1)
d2 = np.diag(np.arange(1, m.shape[0]), k=1)

# получаем индексы, которые удовлетворяют условию
ind1 = np.where(d1>0)
ind2 = np.where(d2>0)

# присвоение значений по индексам
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[ind1] = diag_vec
m[ind2] = diag_vec

print()
print('Вариант 2')
print(m)

# -----------Вариант 3.-----------
# Легкий варинат без создания дополнительной матрицы

# определим функцию, которая возвращает индексы в зависимсоти от смещения (k) матрицы (m)

def diag_indices_k(m, k):
    
    """ функция возвращает индексы диагональных элементов матрицы (m) со смещением (k) """
    
    rows, cols = np.diag_indices_from(m)
    if k < 0:
        return rows[-k:], cols[:k]
    elif k > 0:
        return rows[:-k], cols[k:]
    else:
        return rows, cols

# создаем матрицу (m)

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# проставляем со смещением диагональные значения
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[diag_indices_k(m, -1)] = diag_vec
m[diag_indices_k(m, 1)] = diag_vec

print()
print('Вариант 3')
print(m)



Вариант 1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

Вариант 2
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]

Вариант 3
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]


In [149]:
# 19. Создать матрицу 8x8 и заполнить ее в шахматном порядке
m = np.zeros([8,8])
m[::2, ::2] = 1
m[1::2, 1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [52]:
# 20. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [135]:
# 21. Создать матрицу 8x8 и заполнить ее в шахматном порядке, используя функцию tile

# -----------Вариант 1.-----------
m1 = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
print('вариант 1')
print(m1)
print()
# -----------Вариант 2 (первое что пришло в голову).-----------

# тяжелый вариант
begin = np.array([0,1])
m2 = np.tile(begin, [8,5])

# m2 = np.arange(start=1, stop=65).reshape(8,8)
# print(m)

m2[::2,0:-1] = m2[::2,1:]
m2 = m2[:,:-2]

print()
print('вариант 2')
print(m2)

# проверка на равенство двух матриц
print()
print(np.array_equal(m1, m2))


вариант 1
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


вариант 2
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

True


In [80]:
# 22. Перемножить матрицы 5x3 и 3x2

a = np.random.random([5,3])
b = np.random.random([3,2])
print(np.dot(a,b))


[[0.65988775 0.84825129]
 [0.56543956 0.42502105]
 [0.30422678 0.36332224]
 [0.62463811 0.667436  ]
 [0.58368468 0.77653102]]


In [81]:
# 22.1. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки
m = np.random.randint(low=1, high=100, size=[5,7])
print(m)
print()
d = [3,5]
m = np.delete(arr=m, obj=d, axis=1)
print(m)

[[14 27 30 66 53 13 47]
 [49 67 26 65 11 63 32]
 [37 28 22 57 80 97 13]
 [63 68 83  6 21 93 40]
 [47 56 69 85 76 56 60]]

[[14 27 30 53 47]
 [49 67 26 11 32]
 [37 28 22 80 13]
 [63 68 83 21 40]
 [47 56 69 76 60]]


In [83]:
# 23. Дан массив, поменять знак у элементов, значения которых между 3 и 8
# -----------Вариант 1.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
m[(m > 3) & (m < 8)] *=-1
print(m)
print()

# -----------Вариант 2.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
ind = np.where((m > 3) & (m < 8))
m[ind] *=-1
print(m)

[[23 24 17  9 22]
 [-4 15 13 18  9]
 [20  8 -7 12 14]
 [23 10 12 13 13]
 [-4  2 -7 -7 24]]

[[ 3  8 12  2 13]
 [-4 15 24 -7 15]
 [11 18 23 21  8]
 [ 8 22 14  9 -7]
 [18 10 11 16 23]]


In [84]:
# 24. Создать матрицу 5x5 со значениями в строках от 0 до 4

# -----------Вариант 1.-----------
print('вариант 1')
m = np.zeros([5,5])
m += np.arange(5)
print(m)
print(m.dtype)
print()

# -----------Вариант 2.-----------
print('вариант 2')
m = np.tile(np.arange(5,dtype='float'),[5,1])
print(m)
print(m.dtype)

вариант 1
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64

вариант 2
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64


In [85]:
# 25. Есть генератор, сделать с его помощью массив

# -----------Вариант 1.-----------
# Однако, функция fromiter поддерживает только одномерные массивы (векторы)
def generate():
    for x in range(10):
            yield x
        
m = np.fromiter(generate(), dtype='float', count=-1)
print(m)

# -----------Вариант 2.-----------
# Сделаем, чтобы была возможность преобразовывать и многомерные массивы

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [86]:
# 25.1 Создать двумерный список и преобразовать его в NumPy массив (с типом int32)

list_arr = [[i for i in range(10)] for j in range(10)]
np_arr = np.array(list_arr, dtype='i')
print(np_arr)
print(np_arr.dtype)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
int32


In [91]:
# 26. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

# -----------Вариант 1.-----------
print('вариант 1')
v = np.linspace(start=0, stop=1, num=12)[1:-1]
print(v)
print()
# -----------Вариант 2.-----------
print('вариант 2')
v = np.linspace(0,1,11, endpoint=False)
v = v[1:]
print(v)


вариант 1
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]

вариант 2
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [95]:
# 27. Отсортировать вектор

v = np.random.random(size=[10])
print(v)
print()
v = np.sort(a=v, axis=0)
print(v)


[0.75588505 0.89849978 0.92899815 0.2470675  0.69969153 0.764635
 0.37199536 0.02241758 0.37844922 0.74237717]

[0.02241758 0.2470675  0.37199536 0.37844922 0.69969153 0.74237717
 0.75588505 0.764635   0.89849978 0.92899815]


In [98]:
# 28. Проверить, одинаковы ли 2 NumPy массива

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print('вариант 1')
print(np.array_equal(a,b))
print()
print('вариант 2')
print(np.allclose(a,b))


вариант 1
True

вариант 2
True


In [99]:
# 29. Сделать массив неизменяемым
m = np.zeros([5,5])
m.flags.writeable = False
m[0] = 1

ValueError: assignment destination is read-only

In [100]:
# 30. Дан массив 10x2 (точки в декартовой системе координат),
# нужно преобразовать в полярную

m = np.random.random([10,2])
x,y = m[:,0], m[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)
print(r)
print(t)

[0.57247078 0.57925349 0.17396243 0.59189077 0.99935137 1.1146694
 0.83034403 0.64801259 0.31471921 0.62784216]
[0.97086058 1.53572843 0.90578043 0.57735653 1.25558381 1.09762151
 0.26613598 1.28914798 0.06641493 0.41389478]


In [102]:
# 31. Заменить максимальный элемент на 0

# -----------Вариант 1.-----------

# Однако, если в массиве будут повторяющиеся минимальные или максимальные элементы,
# то присваивание 0 производиться не будет
print('вариант 1')
m = np.random.random([5,5])
m.flatten()[m.argmax()] = 0
print(m)
print()

# -----------Вариант 2.-----------

# при повторяющихся минимальных элементах замена будет производиться везде (корректный вариант)
print('вариант 2')
m = np.random.randint(low=1, high=10, size=[5,5])
m[np.where(m == m.min())] = 0
print(m)
print()

вариант 1
[[0.41048325 0.63118981 0.75896173 0.2886029  0.10199674]
 [0.70271625 0.34552434 0.84829263 0.86080002 0.49455908]
 [0.67117898 0.11016184 0.70892514 0.92309098 0.38738039]
 [0.71898109 0.18020699 0.33907409 0.02171194 0.97855252]
 [0.83656102 0.21380895 0.68643545 0.81234916 0.24676417]]

вариант 2
[[4 3 6 9 6]
 [4 2 9 7 0]
 [0 9 5 9 5]
 [5 2 4 5 0]
 [4 5 6 7 5]]



In [105]:
# 32. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
m = np.zeros([10,10], [('x', float), ('y', float)])
m['x'], m['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))

In [106]:
# 33. Из двух массивов создать матрицу Коши C (Cij = 1/(xi-yj))

a = np.arange(8)
b = a + 0.5
c = 1 / np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.1636371179666


In [107]:
# 34. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# 35. Напечатать все значения в массиве
np.set_printoptions(threshold=np.nan)
m = np.zeros((5, 5))
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [250]:
# 36 Найти ближайшее к заданному значению число в заданном массиве

v = np.random.randint(low=1, high=100, size=[5,5])
v = np.full([3,3], 21)
print(v)

# к данному числу нужно найти ближайшее число в массиве
approx = 21

def find_nearest(a, aim):
    v = np.abs(a - aim)
    idx = np.where(v == v.min())
    return idx

a = find_nearest(v, approx)
a.flatten()

[[21 21 21]
 [21 21 21]
 [21 21 21]]


AttributeError: 'tuple' object has no attribute 'flatten'

In [194]:
def find_nearest(a, a0):
    idx = np.abs(a - a0).argmin()
    return a.flat[idx]

find_nearest(v, approx)

25