In [141]:
# 1. Импортировать NumPy
import numpy as np

In [142]:
# 2. Напечатать версию и конфигурацию
print(np.__version__)

1.14.2


In [143]:
# 3. Создать вектор (одномерный массив) размера 10, заполненый нулями
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [144]:
# 4. Создать вектор размер 10, заполненный единицами
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [145]:
# 5. Создать вектор размера 10, заполненный числом 2.5
np.full([10], 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [172]:
# 6. Получить документацию о функции numpy.add из командной строки
help (np.add)

In [147]:
# 7. Создать вектор заполненный нулями, но пятый элемент равен 1
v = np.zeros([10])
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [148]:
# 8. Создать вектор со значениями от 10 до 49
v = np.arange(start=10,stop=50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [149]:
# 9. Развернуть вектор (первый становится последним)
v = np.arange(start=1, stop=11)
print('вариант 1')
v1 = v[::-1]
print(v1)
print()
print('вариант 2')
v2 = np.flip(v, 0)
print(v2)

вариант 1
[10  9  8  7  6  5  4  3  2  1]

вариант 2
[10  9  8  7  6  5  4  3  2  1]


In [150]:
# 10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
m = np.arange(0,9).reshape(3,3)
np.reshape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
# 11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

# -----------вариант 1.-----------
print('вариант 1')
print(np.nonzero([1,2,0,0,4,0]))
print()

# -----------вариант 2.-----------
print('вариант 2')
v = np.array([1,2,0,0,4,0])
print(np.where(v != 0))

вариант 1
(array([0, 1, 4], dtype=int32),)

вариант 2
(array([0, 1, 4], dtype=int32),)


In [152]:
# 12. Создать единичную матрицу 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [153]:
# 13. Создать массив 3x3x3 со случайными значениями
np.random.random([3,3,3])

array([[[6.47183063e-01, 7.71260775e-01, 5.59117100e-01],
        [3.88301155e-01, 5.44018617e-01, 6.08382095e-01],
        [3.78225715e-01, 2.23609075e-01, 2.49655197e-01]],

       [[4.52037771e-02, 2.75039405e-01, 1.59076222e-01],
        [7.98771669e-01, 1.91862045e-01, 3.77019962e-01],
        [9.77019991e-01, 2.22629682e-01, 1.45784599e-02]],

       [[6.63796618e-01, 2.00689386e-01, 8.33434577e-01],
        [9.97881823e-01, 1.91418194e-01, 1.60708289e-04],
        [4.18044051e-01, 7.65310562e-01, 5.90212240e-01]]])

In [154]:
# 14. Создать массив 10x10 со случайными значениями, найти минимум и максимум
m = np.random.random([10,10])

# -----------вариант 1.-----------
max_var1, max_var2 = m.min(), m.max()
print('варинат 1')
print(max_var1, max_var2)
print()

# -----------вариант 2.-----------
print('вариант 2')
min_var2 = np.min(m)
max_var2 = np.max(m)
print(min_var2)
print(max_var2)

варинат 1
0.004321251270551274 0.9989665554153473

вариант 2
0.004321251270551274
0.9989665554153473


In [155]:
# 15. Создать случайный вектор размера 30 и найти среднее значение всех элементов
v = np.random.random([30])
v.mean()

0.5651997839153932

In [156]:
# 16. Создать матрицу с 0 внутри и 1 на границах

# -----------вариант 1.-----------
m = np.ones([10,10])
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [157]:
# 17. Выяснить результат следующих выражений
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [158]:
# 18. Создать 5x5 матрицу с 1,2,3,4 под диагональю

# -----------Вариант 1.-----------
# Решение в интернете, но я хотел чтобы было добавление с двух сторон k-+1
# и была возможность добавления на существующую матрицу

m = np.diag(np.arange(1, 5), k=-1)

print()
print('Вариант 1')
print(m)

# -----------Вариант 2.-----------
# Тяжелый и неправильный вариант. Созданы 4 лишних переменные.

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# создаем доп. матрицы с нужными диагоналями
d1 = np.diag(np.arange(1, m.shape[0]), k=-1)
d2 = np.diag(np.arange(1, m.shape[0]), k=1)

# получаем индексы, которые удовлетворяют условию
ind1 = np.where(d1>0)
ind2 = np.where(d2>0)

# присвоение значений по индексам
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[ind1] = diag_vec
m[ind2] = diag_vec

print()
print('Вариант 2')
print(m)

# -----------Вариант 3.-----------
# Легкий варинат без создания дополнительной матрицы

# определим функцию, которая возвращает индексы в зависимсоти от смещения (k) матрицы (m)

def diag_indices_k(m, k):
    
    """ функция возвращает индексы диагональных элементов матрицы (m) со смещением (k) """
    
    rows, cols = np.diag_indices_from(m)
    if k < 0:
        return rows[-k:], cols[:k]
    elif k > 0:
        return rows[:-k], cols[k:]
    else:
        return rows, cols

# создаем матрицу (m)

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# проставляем со смещением диагональные значения
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[diag_indices_k(m, -1)] = diag_vec
m[diag_indices_k(m, 1)] = diag_vec

print()
print('Вариант 3')
print(m)



Вариант 1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

Вариант 2
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]

Вариант 3
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]


In [159]:
# 19. Создать матрицу 8x8 и заполнить ее в шахматном порядке
m = np.zeros([8,8])
m[::2, ::2] = 1
m[1::2, 1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [160]:
# 20. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [161]:
# 21. Создать матрицу 8x8 и заполнить ее в шахматном порядке, используя функцию tile

# -----------Вариант 1.-----------
m1 = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
print('вариант 1')
print(m1)
print()
# -----------Вариант 2 (первое что пришло в голову).-----------

# тяжелый вариант
begin = np.array([0,1])
m2 = np.tile(begin, [8,5])

# m2 = np.arange(start=1, stop=65).reshape(8,8)
# print(m)

m2[::2,0:-1] = m2[::2,1:]
m2 = m2[:,:-2]

print()
print('вариант 2')
print(m2)

# проверка на равенство двух матриц
print()
print(np.array_equal(m1, m2))


вариант 1
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


вариант 2
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

True


In [162]:
# 22. Перемножить матрицы 5x3 и 3x2

a = np.random.random([5,3])
b = np.random.random([3,2])
print(np.dot(a,b))

[[0.74625582 0.81045042]
 [0.69089333 0.34331529]
 [0.87353096 0.59906192]
 [0.5327847  0.27981081]
 [0.96224136 0.39763468]]


In [163]:
# 22.1. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

m = np.random.randint(low=1, high=100, size=[5,7])
print(m)
print()
d = [3,5]
m = np.delete(arr=m, obj=d, axis=1)
print(m)

[[77 36 82 17 98 64  7]
 [58 59 75 22 16 85 88]
 [91 90 81 99 52 52 60]
 [94 24 81 58 82 13 36]
 [38 45 28 79 19 37 34]]

[[77 36 82 98  7]
 [58 59 75 16 88]
 [91 90 81 52 60]
 [94 24 81 82 36]
 [38 45 28 19 34]]


In [164]:
# 23. Дан массив, поменять знак у элементов, значения которых между 3 и 8

# -----------Вариант 1.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
m[(m > 3) & (m < 8)] *=-1
print(m)
print()

# -----------Вариант 2.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
ind = np.where((m > 3) & (m < 8))
m[ind] *=-1
print(m)

[[15 -5 -6 -6  2]
 [-6 -4 -6 10  2]
 [-6  2  9 11 20]
 [ 2 14 -5 19 -4]
 [22 17 10 -4 -6]]

[[19 -5 17 14 10]
 [13 21  9 11 17]
 [ 8 20 18 21 12]
 [23 12  8 18 10]
 [-7 17 -5 21 22]]


In [165]:
# 24. Создать матрицу 5x5 со значениями в строках от 0 до 4

# -----------Вариант 1.-----------
print('вариант 1')
m = np.zeros([5,5])
m += np.arange(5)
print(m)
print(m.dtype)
print()

# -----------Вариант 2.-----------
print('вариант 2')
m = np.tile(np.arange(5,dtype='float'),[5,1])
print(m)
print(m.dtype)

вариант 1
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64

вариант 2
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64


In [166]:
# 25. Есть генератор, сделать с его помощью массив

# -----------Вариант 1.-----------
# Однако, функция fromiter поддерживает только одномерные массивы (векторы)
def generate():
    for x in range(10):
            yield x
        
m = np.fromiter(generate(), dtype='float', count=-1)
print(m)

# -----------Вариант 2.-----------
# Сделаем, чтобы была возможность преобразовывать и многомерные массивы

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [167]:
# 25.1 Создать двумерный список и преобразовать его в NumPy массив (с типом int32)

list_arr = [[i for i in range(10)] for j in range(10)]
np_arr = np.array(list_arr, dtype='i')
print(np_arr)
print(np_arr.dtype)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
int32


In [168]:
# 26. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

# -----------Вариант 1.-----------
print('вариант 1')
v = np.linspace(start=0, stop=1, num=12)[1:-1]
print(v)
print()
# -----------Вариант 2.-----------
print('вариант 2')
v = np.linspace(0,1,11, endpoint=False)
v = v[1:]
print(v)


вариант 1
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]

вариант 2
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [169]:
# 27. Отсортировать вектор

v = np.random.random(size=[10])
print(v)
print()
v = np.sort(a=v, axis=0)
print(v)


[0.16613892 0.82906834 0.10340447 0.84207443 0.4517824  0.85853658
 0.17069035 0.16724772 0.66303244 0.19213312]

[0.10340447 0.16613892 0.16724772 0.17069035 0.19213312 0.4517824
 0.66303244 0.82906834 0.84207443 0.85853658]


In [173]:
# 28. Проверить, одинаковы ли 2 NumPy массива

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print('вариант 1')
print(np.array_equal(a,b))
print()
print('вариант 2')
print(np.allclose(a,b))


вариант 1
True

вариант 2
True


In [174]:
# 29. Сделать массив неизменяемым
m = np.zeros([5,5])
m.flags.writeable = False
m[0] = 1

ValueError: assignment destination is read-only

In [177]:
# 30. Дан массив 10x2 (точки в декартовой системе координат),
# нужно преобразовать в полярную

m = np.random.random([10,2])
x,y = m[:,0], m[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)
print(r)
print(t)

[0.16261337 0.90642109 0.84539045 0.98042151 0.90858382 1.15978259
 0.71692483 0.14422626 1.3812284  0.95132496]
[1.35034872 1.53610178 1.44292205 1.27344028 0.00899743 0.96419864
 0.35039065 1.32837489 0.76594261 0.74839165]


In [178]:
# 31. Заменить максимальный элемент на 0

# -----------Вариант 1.-----------

# Однако, если в массиве будут повторяющиеся минимальные или максимальные элементы,
# то присваивание 0 производиться не будет
print('вариант 1')
m = np.random.random([5,5])
m.flatten()[m.argmax()] = 0
print(m)
print()

# -----------Вариант 2.-----------

# при повторяющихся минимальных элементах замена будет производиться везде (корректный вариант)
print('вариант 2')
m = np.random.randint(low=1, high=10, size=[5,5])
m[np.where(m == m.min())] = 0
print(m)
print()

вариант 1
[[0.57877925 0.10099362 0.65782193 0.67349571 0.69891574]
 [0.48644437 0.84377117 0.48371356 0.68968555 0.35036223]
 [0.65652539 0.83244926 0.56946499 0.97651271 0.91136543]
 [0.25315133 0.95059991 0.71178398 0.03280704 0.18713584]
 [0.97376923 0.83537559 0.94677927 0.12921576 0.86711499]]

вариант 2
[[8 3 8 7 8]
 [5 4 2 2 8]
 [8 0 0 8 4]
 [8 2 5 4 5]
 [2 8 5 4 4]]



In [183]:
# 32. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
m = np.zeros([10,10], [('x', float), ('y', float)])
m['x'], m['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))

In [181]:
# 33. Из двух массивов создать матрицу Коши C (Cij = 1/(xi-yj))

a = np.arange(8)
b = a + 0.5
c = 1 / np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.1636371179666


In [184]:
# 34. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [185]:
# 35. Напечатать все значения в массиве
np.set_printoptions(threshold=np.nan)
m = np.zeros((5, 5))
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [186]:
# 36. Найти ближайшее к заданному значению число в заданном массиве

v = np.random.randint(low=1, high=100, size=[5,5])
print(v)

# к данному числу нужно найти ближайшее число в массиве
approx = 21

# -----------Вариант 1.-----------
# (если несколько минимальных элементов, возьмет только один)

print('\nвариант 1')
index = (np.abs(v-approx).argmin())
print(v.flat[index])

# -----------Вариант 2.-----------
# (учитывает несколько вариантов ближайших чисел)

def find_nearest(a, aim):
    """ функция находит индексы минимальных чисел к числу 'aim' """
    v = np.abs(a - aim)
    idx = np.where(v == v.min())
    return idx

# может быть так, что несколько чисел окажутся ближайшими к числу
# напрмер к числу 10 ближайшие 9 и 11
print('\nвариант 2')
a = find_nearest(v, approx)
print('ближайшее(-ие) к числу approx')
print(np.unique(v[a]))

[[35 80 44 23 22]
 [72 48 16 58 50]
 [63 94 59 39 86]
 [87 45 56 36 50]
 [34 12 36 23 53]]

вариант 1
22

вариант 2
ближайшее(-ие) к числу approx
[22]


In [187]:
# 37. Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
Z = np.zeros(10, [ ('position', [('x', float, 1),
                                 ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [233]:
# 38. Дан массив (5,2) координат, найти расстояние от каждой до каждой точки

from scipy.spatial import distance_matrix, distance

m = np.random.randint(low=0, high=100, size=[5,2])
print('массив:')
print(m)

print()
print('вариант 1')
dst = distance_matrix(m, m)
print(dst)

print()
print('вариант 2')
dst2 = distance.cdist(m,m)
print(dst2)


массив:
[[20 84]
 [10 74]
 [ 7 31]
 [60 65]
 [16 60]]

вариант 1
[[ 0.         14.14213562 54.5710546  44.28317965 24.33105012]
 [14.14213562  0.         43.10452412 50.80354318 15.23154621]
 [54.5710546  43.10452412  0.         62.96824597 30.3644529 ]
 [44.28317965 50.80354318 62.96824597  0.         44.28317965]
 [24.33105012 15.23154621 30.3644529  44.28317965  0.        ]]

вариант 2
[[ 0.         14.14213562 54.5710546  44.28317965 24.33105012]
 [14.14213562  0.         43.10452412 50.80354318 15.23154621]
 [54.5710546  43.10452412  0.         62.96824597 30.3644529 ]
 [44.28317965 50.80354318 62.96824597  0.         44.28317965]
 [24.33105012 15.23154621 30.3644529  44.28317965  0.        ]]
