In [3]:
# Импортируем модули
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# 1. Импортировать NumPy
import numpy as np

In [5]:
# 2. Напечатать версию и конфигурацию
print(np.__version__)

1.15.3


In [6]:
# 3. Создать вектор (одномерный массив) размера 10, заполненый нулями
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# 4. Создать вектор размер 10, заполненный единицами
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# 5. Создать вектор размера 10, заполненный числом 2.5
np.full([10], 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [35]:
# 6. Получить документацию о функции numpy.add из командной строки
help (np.add)

In [10]:
# 7. Создать вектор заполненный нулями, но пятый элемент равен 1
v = np.zeros([10])
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
# 8. Создать вектор со значениями от 10 до 49
v = np.arange(start=10, stop=50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# 9. Развернуть вектор (первый становится последним)
v = np.arange(start=1, stop=11)
print('вариант 1')
v1 = v[::-1]
print(v1)

print()
print('вариант 2')
v2 = np.flip(v, 0)
print(v2)

вариант 1
[10  9  8  7  6  5  4  3  2  1]

вариант 2
[10  9  8  7  6  5  4  3  2  1]


In [13]:
# 10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
m = np.arange(0,9).reshape(3,3)
np.reshape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# 11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

# -----------вариант 1.-----------
print('вариант 1')
print(np.nonzero([1,2,0,0,4,0]))
print()

# -----------вариант 2.-----------
print('вариант 2')
v = np.array([1,2,0,0,4,0])
print(np.where(v != 0))

вариант 1
(array([0, 1, 4], dtype=int32),)

вариант 2
(array([0, 1, 4], dtype=int32),)


In [15]:
# 12. Создать единичную матрицу 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 13. Создать массив 3x3x3 со случайными значениями
np.random.random([3,3,3])

array([[[0.78408839, 0.4621633 , 0.6811842 ],
        [0.14644722, 0.71488772, 0.11747033],
        [0.74481802, 0.67388625, 0.90326974]],

       [[0.21816292, 0.23543994, 0.76751447],
        [0.82819672, 0.34355821, 0.94934598],
        [0.74900506, 0.21614656, 0.83371227]],

       [[0.45177433, 0.5967918 , 0.6077558 ],
        [0.56457179, 0.88695473, 0.68545813],
        [0.58030458, 0.10399959, 0.84043154]]])

In [17]:
# 14. Создать массив 10x10 со случайными значениями, найти минимум и максимум
m = np.random.random([10,10])

# -----------вариант 1.-----------
max_var1, max_var2 = m.min(), m.max()
print('варинат 1')
print(max_var1, max_var2)
print()

# -----------вариант 2.-----------
print('вариант 2')
min_var2 = np.min(m)
max_var2 = np.max(m)
print(min_var2)
print(max_var2)

варинат 1
0.0031040568187371553 0.9829250751255604

вариант 2
0.0031040568187371553
0.9829250751255604


In [18]:
# 15. Создать случайный вектор размера 30 и найти среднее значение всех элементов
v = np.random.random([30])
v.mean()

0.5410328394304684

In [19]:
# 16. Создать матрицу с 0 внутри и 1 на границах

# -----------вариант 1.-----------
m = np.ones([10,10])
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
# 17. Выяснить результат следующих выражений
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [21]:
# 18. Создать 5x5 матрицу с 1,2,3,4 под диагональю

# -----------Вариант 1.-----------
# Решение в интернете, но я хотел чтобы было добавление с двух сторон k-+1
# и была возможность добавления на существующую матрицу

m = np.diag(np.arange(1, 5), k=-1)

print()
print('Вариант 1')
print(m)

# -----------Вариант 2.-----------
# Тяжелый и неправильный вариант. Созданы 4 лишних переменные.

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# создаем доп. матрицы с нужными диагоналями
d1 = np.diag(np.arange(1, m.shape[0]), k=-1)
d2 = np.diag(np.arange(1, m.shape[0]), k=1)

# получаем индексы, которые удовлетворяют условию
ind1 = np.where(d1>0)
ind2 = np.where(d2>0)

# присвоение значений по индексам
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[ind1] = diag_vec
m[ind2] = diag_vec

print()
print('Вариант 2')
print(m)

# -----------Вариант 3.-----------
# Легкий варинат без создания дополнительной матрицы

# определим функцию, которая возвращает индексы в зависимсоти от смещения (k) матрицы (m)

def diag_indices_k(m, k):
    
    """ функция возвращает индексы диагональных элементов матрицы (m) со смещением (k) """
    
    rows, cols = np.diag_indices_from(m)
    if k < 0:
        return rows[-k:], cols[:k]
    elif k > 0:
        return rows[:-k], cols[k:]
    else:
        return rows, cols

# создаем матрицу (m)

# m = np.arange(1, 26).reshape([5,5])
m = np.zeros([5,5], dtype='i')

# проставляем со смещением диагональные значения
diag_vec = np.arange(start=1, stop=5, dtype='i')
m[diag_indices_k(m, -1)] = diag_vec
m[diag_indices_k(m, 1)] = diag_vec

print()
print('Вариант 3')
print(m)



Вариант 1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

Вариант 2
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]

Вариант 3
[[0 1 0 0 0]
 [1 0 2 0 0]
 [0 2 0 3 0]
 [0 0 3 0 4]
 [0 0 0 4 0]]


In [22]:
# 19. Создать матрицу 8x8 и заполнить ее в шахматном порядке
m = np.zeros([8,8])
m[::2, ::2] = 1
m[1::2, 1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [23]:
# 20. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [24]:
# 21. Создать матрицу 8x8 и заполнить ее в шахматном порядке, используя функцию tile

# -----------Вариант 1.-----------
m1 = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
print('вариант 1')
print(m1)
print()
# -----------Вариант 2 (первое что пришло в голову).-----------

# тяжелый вариант
begin = np.array([0,1])
m2 = np.tile(begin, [8,5])

# m2 = np.arange(start=1, stop=65).reshape(8,8)
# print(m)

m2[::2,0:-1] = m2[::2,1:]
m2 = m2[:,:-2]

print()
print('вариант 2')
print(m2)

# проверка на равенство двух матриц
print()
print(np.array_equal(m1, m2))


вариант 1
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


вариант 2
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

True


In [25]:
# 22. Перемножить матрицы 5x3 и 3x2

a = np.random.random([5,3])
b = np.random.random([3,2])
print(np.dot(a,b))

[[0.69842778 1.5462586 ]
 [0.22437342 0.50542636]
 [0.40027503 0.84496098]
 [0.28613926 0.63206989]
 [0.62381023 1.36620206]]


In [26]:
# 22.1. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

m = np.random.randint(low=1, high=100, size=[5,7])
print(m)
print()
d = [3,5]
m = np.delete(arr=m, obj=d, axis=1)
print(m)

[[62 45 49 15  8 95 87]
 [94 79 35 48 46 74 15]
 [73 48 23 75  8 16  7]
 [89 30 87 46 96 10 37]
 [29 12 96 74 93 82 70]]

[[62 45 49  8 87]
 [94 79 35 46 15]
 [73 48 23  8  7]
 [89 30 87 96 37]
 [29 12 96 93 70]]


In [27]:
# 23. Дан массив, поменять знак у элементов, значения которых между 3 и 8

# -----------Вариант 1.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
m[(m > 3) & (m < 8)] *=-1
print(m)
print()

# -----------Вариант 2.-----------
m = np.random.randint(low=1, high=25, size=[5,5])
ind = np.where((m > 3) & (m < 8))
m[ind] *=-1
print(m)

[[23 22  1 22 23]
 [16 20  2 15 -4]
 [-5 19 11  3  3]
 [-5 12 19 21 21]
 [12 10  3 23 19]]

[[24 -4 14 21 23]
 [16 -7 18  9 18]
 [11 22 22 23 13]
 [-7 15  1  1 20]
 [24 13 10 13 -4]]


In [28]:
# 24. Создать матрицу 5x5 со значениями в строках от 0 до 4

# -----------Вариант 1.-----------
print('вариант 1')
m = np.zeros([5,5])
m += np.arange(5)
print(m)
print(m.dtype)
print()

# -----------Вариант 2.-----------
print('вариант 2')
m = np.tile(np.arange(5,dtype='float'),[5,1])
print(m)
print(m.dtype)

вариант 1
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64

вариант 2
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
float64


In [29]:
# 25. Есть генератор, сделать с его помощью массив

# -----------Вариант 1.-----------
# Однако, функция fromiter поддерживает только одномерные массивы (векторы)
def generate():
    for x in range(10):
            yield x
        
m = np.fromiter(generate(), dtype='float', count=-1)
print(m)

# -----------Вариант 2.-----------
# Сделаем, чтобы была возможность преобразовывать и многомерные массивы

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [30]:
# 25.1 Создать двумерный список и преобразовать его в NumPy массив (с типом int32)

list_arr = [[i for i in range(10)] for j in range(10)]
np_arr = np.array(list_arr, dtype='i')
print(np_arr)
print(np_arr.dtype)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
int32


In [31]:
# 26. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

# -----------Вариант 1.-----------
print('вариант 1')
v = np.linspace(start=0, stop=1, num=12)[1:-1]
print(v)
print()
# -----------Вариант 2.-----------
print('вариант 2')
v = np.linspace(0,1,11, endpoint=False)
v = v[1:]
print(v)


вариант 1
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]

вариант 2
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [32]:
# 27. Отсортировать вектор

v = np.random.random(size=[10])
print(v)
print()
v = np.sort(a=v, axis=0)
print(v)


[0.77884163 0.01490805 0.78701506 0.1702387  0.29832726 0.55938952
 0.41948636 0.2020511  0.61233324 0.35043127]

[0.01490805 0.1702387  0.2020511  0.29832726 0.35043127 0.41948636
 0.55938952 0.61233324 0.77884163 0.78701506]


In [33]:
# 28. Проверить, одинаковы ли 2 NumPy массива

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print('вариант 1')
print(np.array_equal(a,b))
print()
print('вариант 2')
print(np.allclose(a,b))


вариант 1
True

вариант 2
True


In [34]:
# 29. Сделать массив неизменяемым
m = np.zeros([5,5])
m.flags.writeable = False
m[0] = 1

ValueError: assignment destination is read-only

In [ ]:
# 30. Дан массив 10x2 (точки в декартовой системе координат),
# нужно преобразовать в полярную

m = np.random.random([10,2])
x,y = m[:,0], m[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)
print(r)
print(t)